<a href="https://colab.research.google.com/github/pentakotalokesh/Numpy-Lab/blob/main/LAB_NUMPY%20-%202%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2.NumPy Basics (np.array, np.arrange, np.linespace, np.zeros, np.ones,
np.random.random, np.empty)

In [4]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


To Create an ndarray,we can pass a list,tuple or nay array-like object into the array()method and it will be converted into an ndarray

In [5]:
b=np.array((1,2,3,4))
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


Dimension in array
nested array:are arrays as their elements

In [12]:
#0-D array
arr=np.array([42])
print(arr)

[42]


In [9]:
#1-D array
arr1=np.array([8,6,3,9,6,3,6,3,9,3])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#2-D array
arr2=np.array([[1,2,3,4],
             [5,6,7,8]])
print(arr)


[[1 2 3 4]
 [5 6 7 8]]


Check number of dimensions ndim


In [13]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
1
2


numpy arrange


In [16]:
arr3=np.arange(3)
arr4=np.arange(5,10)
arr5=np.arange(3,7,2)

In [17]:
print(arr3)
print(arr4)
print(arr5)

[0 1 2]
[5 6 7 8 9]
[3 5]


linspace:It Gives Evenly Linespace in ndarray between numbers

In [19]:
arr6=np.linspace(2,3,num=5)
print(arr6)

[2.   2.25 2.5  2.75 3.  ]


np.zeros: is used to get all zeros matrix in any dimension

In [22]:
arr7=np.zeros((3,3,),dtype=int)
print(arr7)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


np.ones:is used to get all ones matrix

In [23]:
arr8=np.ones((3,3),dtype=int)
print(arr8)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


np.random.random:is one of the function for doing random sampling in numpy.
It returns an array of specified shape and fills it with random floats in the half open interval

[0.0,1.0)

In [24]:
arr9=np.random.random(5)
print(arr9)

[0.62552848 0.89506733 0.41646548 0.71389882 0.42322657]


In [25]:
arr10=np.empty([3,3],dtype=int)
print(arr10)

[[     94109989229888                  42      94111323389951]
 [7147042649926496103 7451595014149599084 3636198724363187569]
 [7867629619916206127 8030604430244406383 7349986125609463668]]
